### ISSUE TITLE
Support for portable classes

### ISSUE THREAD

**Issue by NilesDavis** [dajuric/dot-imaging#13]
Is there any chance to get this working as portable class library PCL?

**Comment by dajuric** [comment]
The incoming release will be .NET Core 2 compatible.

**Comment by NilesDavis** [comment]
Can I reference a Net Core 2.0 project from a PCL? I didn't know that

**Comment by dajuric** [comment]
When I have tried to rewrite the library using the PCL, there were many
obstacles which could not be removed at the time.
I do not know much about the PCL, but it seems that they are replaced with
netstandard (or netcoreapp2.0) (
https://stackoverflow.com/questions/40514546/difference-between-net-core-portable-standard-compact-uwp-and-pcl
).

How to migrate projects:
https://blogs.msdn.microsoft.com/premier_developer/2017/10/27/converting-pcl-portable-class-libraries-libraries-to-net-standard-class-libraries/

2018-02-12 0:31 GMT+01:00 NilesDavis <notifications@github.com>:
