### ISSUE TITLE
DotImaging.ImageIO not 'visible' in .NET core 2.0 on windows

### ISSUE THREAD

**Issue by dcarapic** [dajuric/dot-imaging#15]
When I add the package DotImaging.IO in my .NET Core 2.0 project under windows in Visual Studio the ImageIO class is not visible. The nuget also tells me:

xxx.csproj : warning NU1701: Package 'DotImaging.GenericImage 4.8.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.
xxx.csproj : warning NU1701: Package 'DotImaging.Primitives2D 4.8.3' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by dajuric** [comment]
Yes, because the current package version targets 4.6.1 version. the
upcoming version will target .NET Core 2.0.

2018-02-25 10:54 GMT+01:00 Dalibor Čarapić <notifications@github.com>:

**Comment by dcarapic** [comment]
Ok, thank you. I was under the impression that the 4.8.3 works with .NET Core 2.0.
My bad. You can close this ticket.
