### ISSUE TITLE
No dependencies?

### ISSUE THREAD

**Issue by fdncred** [dajuric/dot-imaging#2]
I don't understand this comment in the readme file.

```
lightweight (no 3rd party dependencies), but powerful
```

Dot-Imaging has OpenCV dependencies in the Source/IO/UnmanagedLibraries folder.  Please help me understand.  Thanks.

**Comment by dajuric** [comment]
I agree I could formulate the statement better.
I meant that there are no managed dependencies (no 3rd party NuGet packages or 3rd party managed libraries).

Comments are welcome.

**Comment by scotlunsford** [comment]
Also, the unmanaged libraries have a dependency on the Visual C++ 2010 Redistributable Package.

**Comment by dajuric** [comment]
The bullet-point has been changed.
