### ISSUE TITLE
Unicode Filename

### ISSUE THREAD

**Issue by mtss92** [dajuric/dot-imaging#6]
Hi
I'm using FileCapture. all things worked corrcetly but when i use video file with Unicode name i get this error:
"Cannot open FileStream!"

**Comment by tesar-tech** [comment]
Same issue here.

We can track it somewhere to this line: https://github.com/dajuric/dot-imaging/blob/b6a987643ef8358c9362c296826096dfbfd5c742/Source/IO/Readers/FileCapture.cs#L85

After the calling of https://github.com/dajuric/dot-imaging/blob/b6a987643ef8358c9362c296826096dfbfd5c742/Source/IO/Readers/FileCapture.cs#L83

Which is OpenCV function.
https://github.com/dajuric/dot-imaging/blob/b6a987643ef8358c9362c296826096dfbfd5c742/Source/IO/Base/CvInvoke.cs#L220


And probably this issue: https://github.com/opencv/opencv/issues/4292 has something common with this one...
