### ISSUE TITLE
Compile without OpenCv Dependencies?

### ISSUE THREAD

**Issue by fdncred** [dajuric/dot-imaging#8]
If I don't care about OpenCv Interoperability or Drawing on images, is there a way to compile this library so there are no need for the opencv unmanaged dlls?

I'd like to use these assemblies, just not the opencv stuff.

Thanks,
Darren

**Comment by dajuric** [comment]
Yeah, sure. Just remove DotImaging.IO and DotImaging.Drawing projects. The rest of the projects are not dependent on OpenCV.* libraries.

**Comment by fdncred** [comment]
Thanks. Follow up question. If I don't use DotImaging.IO, how do I load an image into something like a Gray<byte>[,]?

**Comment by dajuric** [comment]
Using DotImaging.BitmapInterop or DotImaging.BitmapSourceInterop.

Example on Github page (readme).

**Comment by fdncred** [comment]
Thanks for the tip!  Here's another follow up.

I'm trying to write a Generic that returns multiple types. I understand that C# doesn't allow that necessarily. I wanted to know if you have a better idea of how to write this helper method.

I want to call it like this, allowing the user to specify the return type during load.
```cs
var imgFile= LoadFileAs<Gray<byte>>(fileName);
```
This is the current method that works but I'm cautious about using dynamic and was hoping there was another way.
```cs
private dynamic LoadFileAs<T>(string fileName) where T: struct, IColor
{
    var fileAsBitmap = Accord.Imaging.Image.FromFile(fileName);
    Bitmap fileAsColorBitmap = default(Bitmap);
    if (fileAsBitmap.PixelFormat == PixelFormat.Format1bppIndexed)
    {
        fileAsColorBitmap = fileAsBitmap.Clone(new System.Drawing.Rectangle(0, 0, fileAsBitmap.Width, fileAsBitmap.Height), PixelFormat.Format24bppRgb);
        fileAsBitmap.Dispose();
    }
    else
        fileAsColorBitmap = fileAsBitmap;

    Type imgType = typeof(T);
    if (imgType == typeof(Bgr<byte>))
        return fileAsColorBitmap.ToArray().ToBgr();
    else if (imgType == typeof(Bgra<byte>))
        return fileAsColorBitmap.ToArray().ToBgra();
    else if (imgType == typeof(Gray<byte>))
        return fileAsColorBitmap.ToArray().ToGray();
    else if (imgType == typeof(Bgr<float>))
        return fileAsColorBitmap.ToArray().ToBgr().ConvertChannelDepth<Bgr<byte>, Bgr<float>>();
    else if (imgType == typeof(Bgra<float>))
        return fileAsColorBitmap.ToArray().ToBgra().ConvertChannelDepth<Bgra<byte>, Bgra<float>>();
    else if (imgType == typeof(Gray<float>))
        return fileAsColorBitmap.ToArray().ToGray().ConvertChannelDepth<Gray<byte>, Gray<float>>();
    else if (imgType == typeof(Bgr<int>))
        return fileAsColorBitmap.ToArray().ToBgr().ConvertChannelDepth<Bgr<byte>, Bgr<int>>();
    else if (imgType == typeof(Bgra<int>))
        return fileAsColorBitmap.ToArray().ToBgra().ConvertChannelDepth<Bgra<byte>, Bgra<int>>();
    else if (imgType == typeof(Gray<int>))
        return fileAsColorBitmap.ToArray().ToGray().ConvertChannelDepth<Gray<byte>, Gray<int>>();
    else
        throw new NotSupportedException();
}
```
**Update**
I take it back, my dynamic method doesn't work. It's converting everything to an Array type. So in order to use it I have to do something like this, which defeats the purpose of passing in the type to begin with.
```cs
var imgFile= LoadFileAs<Gray<byte>>(fileName).ToGray();
```

**Comment by dajuric** [comment]
Hi Darren,

   why the function signature is not like this:
private T[,] LoadAsFile<T>(string fileName) where T: struct: IColor

Did you have any difficulties with it ?

Best,
Darko

2017-10-10 14:56 GMT+02:00 Darren Schroeder <notifications@github.com>:

**Comment by fdncred** [comment]
Hey Darko,
Thanks for responding.

If I use T[,] as the return type of the generic method, I get an error on every line that has something like "return fileAsColorBitmap.ToArray().ToBgr()".  That error is below.

| Severity | Code |Description
| -------- | ---- | -----------
|Error	|CS0029	|Cannot implicitly convert type 'DotImaging.Bgr<byte>[*,*]' to 'T[*,*]'	

Darren

**Comment by dajuric** [comment]
Hi Darren,

   you can do it like this:

public static T[,] LoadFileAs<T>(string fileName)
            where T: IColor<byte>
{
     var bmp = Image.FromFile(fileName); //System.Drawing
     var img = (bmp as Bitmap).ToArray();  //Bitmap extension
(BitmapInterop package)
     return img as T[,];                                //will be casted to
wanted array or will return null
 }

Is that what you are looking for ?

2017-10-11 14:39 GMT+02:00 Darren Schroeder <notifications@github.com>:

**Comment by dajuric** [comment]
(you may use IColor wihtout 'byte' constraint)

ToArray() conversions:
https://github.com/dajuric/dot-imaging/blob/master/Source/BitmapInterop/BitmapConversion.cs
 (line 55)

2017-10-11 16:18 GMT+02:00 Darko Jurić <darko.juric2@gmail.com>:

**Comment by dajuric** [comment]
(and it maybe better to name the function TryLoadFileAs since in some cases
the file will be loaded, but the constraint you specify will not be the
same as loaded image, so null will be returned.

2017-10-11 16:20 GMT+02:00 Darko Jurić <darko.juric2@gmail.com>:

**Comment by fdncred** [comment]
While your idea doesn't work like I needed it to, it did help me figure out a way to do it by combining your ideas and mine. This is the result.
```cs
public static T[,] LoadFileAs<T>(string fileName) where T: IColor
{
    var fileAsBitmap = (Bitmap)Bitmap.FromFile(fileName);

    // Create a Color Bitmap since 1bpp isn't supported
    Bitmap fileAsColorBitmap = default(Bitmap);
    if (fileAsBitmap.PixelFormat == PixelFormat.Format1bppIndexed)
    {
        fileAsColorBitmap = fileAsBitmap.Clone(PixelFormat.Format24bppRgb);
        fileAsBitmap.Dispose();
    }
    else
        fileAsColorBitmap = fileAsBitmap;

    Type imgType = typeof(T);
    if (imgType == typeof(Bgr<byte>))
        return fileAsColorBitmap.ToArray().ToBgr() as T[,];
    else if (imgType == typeof(Bgra<byte>))
        return fileAsColorBitmap.ToArray().ToBgra()as T[,];
    else if (imgType == typeof(Gray<byte>))
        return fileAsColorBitmap.ToArray().ToGray() as T[,];
    else if (imgType == typeof(Bgr<float>))
        return fileAsColorBitmap.ToArray().ToBgr().ConvertChannelDepth<Bgr<byte>, Bgr<float>>() as T[,];
    else if (imgType == typeof(Bgra<float>))
        return fileAsColorBitmap.ToArray().ToBgra().ConvertChannelDepth<Bgra<byte>, Bgra<float>>() as T[,];
    else if (imgType == typeof(Gray<float>))
        return fileAsColorBitmap.ToArray().ToGray().ConvertChannelDepth<Gray<byte>, Gray<float>>() as T[,];
    else if (imgType == typeof(Bgr<int>))
        return fileAsColorBitmap.ToArray().ToBgr().ConvertChannelDepth<Bgr<byte>, Bgr<int>>() as T[,];
    else if (imgType == typeof(Bgra<int>))
        return fileAsColorBitmap.ToArray().ToBgra().ConvertChannelDepth<Bgra<byte>, Bgra<int>>() as T[,];
    else if (imgType == typeof(Gray<int>))
        return fileAsColorBitmap.ToArray().ToGray().ConvertChannelDepth<Gray<byte>, Gray<int>>() as T[,];
    else
        throw new NotSupportedException();
}
```
Now I have a generic method that the user can call to specify what format they want the image returned in.

Thanks for all your help! Feel free to close this ticket.

**Comment by dajuric** [comment]
You are welcome.
